FROM python:3.8.1-slim-buster
WORKDIR /home/application

COPY requirements.txt requirements.txt
COPY celery_boot.sh celery_boot.sh
RUN python -m venv task
RUN task/bin/pip install -r requirements.txt

RUN chmod +x boot.sh

ENTRYPOINT ["sh", "./celery_boot.sh" ]