FROM python:3.8.1-slim-buster

RUN adduser task

WORKDIR /home/task

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . ./
RUN chmod +x celery_boot.sh

RUN chown -R task:task ./
USER task

ENTRYPOINT ["sh", "./celery_boot.sh"]