"""empty message

Revision ID: 37965bfbfaae
Revises: a814f3a5309a
Create Date: 2021-02-08 13:56:27.330063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37965bfbfaae'
down_revision = 'a814f3a5309a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_table('roles_users')
    # ### end Alembic commands ###
