"""empty message

Revision ID: 5e5df9b078ce
Revises: 9087525421e3
Create Date: 2021-02-09 00:17:06.218467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5df9b078ce'
down_revision = '9087525421e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('article_user_fkey', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'user', ['user_id'], ['id'])
    op.drop_column('article', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key('article_user_fkey', 'article', 'user', ['user'], ['id'])
    op.drop_column('article', 'user_id')
    # ### end Alembic commands ###
